export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_ARTICLES_BY_TOPIC_REQUEST = 'FETCH_ARTICLES_BY_TOPIC_REQUEST';
export const FETCH_ARTICLES_BY_TOPIC_SUCCESS = 'FETCH_ARTICLES_BY_TOPIC_SUCCESS';
export const FETCH_ARTICLES_BY_TOPIC_FAILURE = 'FETCH_ARTICLES_BY_TOPIC_FAILURE';

export const FETCH_ARTICLE_BY_ID_REQUEST = 'FETCH_ARTICLE_BY_ID_REQUEST';
export const FETCH_ARTICLE_BY_ID_SUCCESS = 'FETCH_ARTICLE_BY_ID_SUCCESS';
export const FETCH_ARTICLE_BY_ID_FAILURE = 'FETCH_ARTICLE_BY_ID_FAILURE';

export const FETCH_COMMENTS_BY_ARTICLE_REQUEST = 'FETCH_COMMENTS_BY_ARTICLE_REQUEST';
export const FETCH_COMMENTS_BY_ARTICLE_SUCCESS = 'FETCH_COMMENTS_BY_ARTICLE_SUCCESS';
export const FETCH_COMMENTS_BY_ARTICLE_FAILURE = 'FETCH_COMMENTS_BY_ARTICLE_FAILURE';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';
